/**
 * This is an example of an atom decorator that will modify the behaviour of
 * an already initialised atom. `withOutput` specifically takes an output
 * that has been generated by the fn() and pipes that as an input to the
 * passed in atomFn.
 * @param {function} atomFn
 * @param {number} offset
 */
export default function withOutput(atomFn, offset) {
  return function _withOutput() {
    return atomFn.call(this, this.getOutput(offset));
  };
}
